sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: sky
    password: 123
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  minio:
    endpoint: http://localhost:9000
    access-key-id: sky
    access-key-secret: 12345678
    bucket-name: sky-take-out
